name: Sync Archive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: anatawa12/fork-sync-all-branches@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
